#!/usr/bin/env bash
# gpt2api <-> shared Caddy entrypoint sync.
#
# The shared Caddyfile is generated by claude-relay-service. Service-specific
# routes must live in /opt/claude-relay-service/caddy/config/sites.d so one
# service deployment does not overwrite another service entrypoint.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SNIPPET="$REPO_ROOT/deploy/caddy/gpt.sora.locker.caddy"

CADDY_DIR="/opt/claude-relay-service/caddy"
CADDYFILE="$CADDY_DIR/Caddyfile"
CADDY_TEMPLATE="$CADDY_DIR/Caddyfile.template"
SITES_DIR="$CADDY_DIR/config/sites.d"
TARGET_SNIPPET="$SITES_DIR/gpt2api.caddy"
CADDY_CONTAINER="compose-caddy-1"
IMPORT_LINE="import /config/sites.d/*.caddy"

BEGIN_MARK="# ===== BEGIN gpt2api-managed (自动维护,请勿手改) ====="
END_MARK="# ===== END gpt2api-managed ====="

log() { echo "[sync-caddy] $*"; }
warn() { echo "[sync-caddy] WARN: $*" >&2; }

if [ ! -f "$SNIPPET" ]; then
    warn "snippet not found: $SNIPPET - skip"
    exit 0
fi
if [ ! -f "$CADDYFILE" ]; then
    warn "Caddyfile not found: $CADDYFILE - skip"
    exit 0
fi

if ! sudo mkdir -p "$SITES_DIR"; then
    warn "cannot create sites dir: $SITES_DIR - skip"
    exit 0
fi

sudo python3 - "$CADDYFILE" "$CADDY_TEMPLATE" "$SNIPPET" "$TARGET_SNIPPET" "$IMPORT_LINE" "$BEGIN_MARK" "$END_MARK" <<'PY'
import pathlib
import sys

caddyfile, template, snippet_path, target_path, import_line, begin, end = sys.argv[1:8]


def ensure_import(path: pathlib.Path) -> bool:
    if not path.exists():
        return False
    content = path.read_text()
    if import_line in content:
        return False
    if not content.endswith("\n"):
        content += "\n"
    content += "\n# Shared service entrypoints. Keep service-specific domains outside the generated block.\n"
    content += import_line + "\n"
    path.write_text(content)
    return True


def remove_managed_block(path: pathlib.Path) -> bool:
    content = path.read_text()
    if begin not in content and end not in content:
        return False
    if begin not in content or end not in content:
        raise SystemExit("Caddyfile has only one gpt2api marker; manual repair required")
    start = content.index(begin)
    stop = content.index(end, start) + len(end)
    while stop < len(content) and content[stop] in " \t\r\n":
        stop += 1
    new_content = content[:start].rstrip() + "\n\n" + content[stop:]
    path.write_text(new_content)
    return True


snippet = pathlib.Path(snippet_path).read_text()
target = pathlib.Path(target_path)
old = target.read_text() if target.exists() else None
if old != snippet:
    target.write_text(snippet)
    print("[sync-caddy] wrote sites.d/gpt2api.caddy")
else:
    print("[sync-caddy] no-op sites.d/gpt2api.caddy")

changed_template = ensure_import(pathlib.Path(template))
changed_caddyfile = ensure_import(pathlib.Path(caddyfile))
removed = remove_managed_block(pathlib.Path(caddyfile))

if changed_template:
    print("[sync-caddy] added sites.d import to Caddyfile.template")
if changed_caddyfile:
    print("[sync-caddy] added sites.d import to Caddyfile")
if removed:
    print("[sync-caddy] removed legacy gpt2api-managed block from Caddyfile")
PY
PY_RC=$?
if [ "$PY_RC" -ne 0 ]; then
    warn "Caddy sync failed (rc=$PY_RC) - skip reload"
    exit 0
fi

if ! sudo docker exec "$CADDY_CONTAINER" caddy validate \
        --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
    warn "caddy validate failed"
    sudo docker exec "$CADDY_CONTAINER" caddy validate \
        --config /etc/caddy/Caddyfile --adapter caddyfile 2>&1 | tail -20 >&2
    exit 0
fi

if sudo docker exec "$CADDY_CONTAINER" caddy reload \
        --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null 2>&1; then
    log "caddy reload ok - gpt.sora.locker synced via sites.d"
else
    warn "caddy reload failed"
fi
